const $=id=>document.getElementById(id);
const SAVE_KEY="escape_asylum_management_demo_v3";
const WEEK=["周一","周二","周三","周四","周五","周六","周日"];
const clueMeta={
  wristband:{name:"错误腕带编号",type:"身份异常",text:"腕带姓名与病历页码不一致。编号 E2-071 可以与正式病历交叉核对。",impact:"解锁病历柜的身份核查方向。"},
  notice:{name:"每周治疗排班",type:"周期情报",text:"周一、周三、周五开放行政登记；周二、周四、周六开放工疗室。周五晚联合清点病历与药品。",impact:"开放依据星期安排调查的周期玩法。"},
  nightRoster:{name:"异常夜班记录",type:"人物情报",text:"老张确认，同一名院外人员每周二、周五深夜进入行政区，却没有出现在公开访客表里。",impact:"把治疗排班与院外人员活动连接起来。"},
  drugBatch:{name:"重复药品批次",type:"物证线索",text:"药品车上的批号被重复登记，而其中一箱并未进入当日治疗记录。",impact:"病历柜调查不再只是身份争议，而能核对药品去向。"},
  records:{name:"病历复写页",type:"关键证据",text:"复写页显示 E2-071 曾属于另一名已经出院的病人，你的档案是后来补入同一编号的。",impact:"形成可供院外复核的正式记录证据。"},
  maintenance:{name:"旧楼检修路线",type:"路线线索",text:"维修门后的编号与陈伯记忆一致。周五清点时，西侧检修廊有四十分钟无人巡查。",impact:"开放维修通道逃离方案的核心路径。"}
};
const itemMeta={
  tea:{name:"茶包",price:6,desc:"老张一直想喝一杯像样的茶。"},snack:{name:"点心",price:5,desc:"陈伯愿意为了这点甜味多说几句话。"},soap:{name:"香皂",price:6,desc:"使用后信任 +2、怀疑 -6。"},carbon:{name:"复写纸",price:8,desc:"复制正式记录而不取走原件。"},coffee:{name:"速溶咖啡",price:7,desc:"夜班保安周凯的唯一提神方式。"},flashlight:{name:"袖珍手电",price:null,desc:"陈伯保留的维修工具。"}
};
const scenes={
  ward:{title:"东区 2 号病房",hint:"床铺恢复状态，床头柜藏着最初的身份矛盾。",people:["nurse"],hotspots:[["rest","休息",17,62],["locker","储物柜",82,45],["wristband","陌生腕带",50,56]]},
  garden:{title:"康复花园",hint:"院友关系会把传闻变成可验证的路线和时间。",people:["zhang","chen"],hotspots:[["zhang","老张",27,63],["exercise","康复训练",62,47],["chen","陈伯",83,63]]},
  workshop:{title:"工疗工作坊",hint:"周二、周四、周六开放；工作、物资和旧楼路线在这里交汇。",people:["guard"],hotspots:[["work","工疗台",27,59],["laundry","洗衣车",61,65],["maintenance","维修门",78,45],["guard","保安周凯",89,58]]},
  station:{title:"护士站与行政走廊",hint:"周一、周三、周五开放登记；高价值线索也意味着更高风险。",people:["nurse","guard"],hotspots:[["records","病历柜",24,45],["notice","排班公告",54,42],["cart","药品车",72,59],["nurse","护士林",88,62]]}
};
const personMeta={nurse:{name:"护士林",short:"林"},zhang:{name:"老张",short:"张"},chen:{name:"陈伯",short:"陈"},guard:{name:"保安周凯",short:"周"}};
let S,toastTimer,shopFirst=false,pendingClue=null,gameStarted=false;

function defaultState(){return{version:3,day:1,time:8,energy:92,clarity:84,tokens:18,trust:52,suspicion:8,drug:0,scene:"ward",morning:false,dayEnded:false,chapterShown:false,
  relations:{nurse:5,zhang:8,chen:0,guard:0},inventory:{tea:0,snack:1,soap:0,carbon:0,coffee:0,flashlight:0},clues:{wristband:false,notice:false,nightRoster:false,drugBatch:false,records:false,maintenance:false},flags:{zhangGift:false,chenGift:false,guardGift:false,laundryFound:false},skills:{fitness:1,social:1,observe:1},logs:[{day:1,time:8,text:"你在东区 2 号病房醒来。床头柜上放着一只不属于你的腕带。",changes:[]}]}}
function merge(saved){const b=defaultState(),s={...b,...saved};["relations","inventory","clues","flags","skills"].forEach(k=>s[k]={...b[k],...(saved[k]||{})});s.logs=Array.isArray(saved.logs)?saved.logs.slice(-60):b.logs;return s}
function clamp(v,a=0,b=100){return Math.max(a,Math.min(b,v))}
function weekday(){return WEEK[(S.day-1)%7]}
function weekNo(){return((S.day-1)%7)+1}
function drugEffect(){if(S.drug>=80)return{name:"意识模糊",time:1.6,energy:8,growth:.45};if(S.drug>=65)return{name:"重度镇静",time:1.4,energy:6,growth:.6};if(S.drug>=50)return{name:"明显迟钝",time:1.3,energy:4,growth:.72};if(S.drug>=25)return{name:"轻度迟钝",time:1.15,energy:2,growth:.88};return{name:"头脑清醒",time:1,energy:0,growth:1}}
function normalize(){["energy","clarity","trust","suspicion","drug"].forEach(k=>S[k]=clamp(Number(S[k])||0));S.tokens=Math.max(0,Math.round(S.tokens));S.time=clamp(Math.round(S.time),8,22)}
function snapshot(){return{time:S.time,energy:S.energy,clarity:S.clarity,tokens:S.tokens,trust:S.trust,suspicion:S.suspicion,drug:S.drug,relations:{...S.relations},inventory:{...S.inventory},skills:{...S.skills}}}
function changes(before){const out=[],fields={energy:["体力",true],clarity:["清醒",true],tokens:["积分",true],trust:["信任",true],suspicion:["怀疑",false],drug:["药物",false]};for(const [k,[name,goodHigh]] of Object.entries(fields)){const d=S[k]-before[k];if(d)out.push({text:`${name} ${d>0?"+":""}${d}`,good:(d>0)===goodHigh})}const td=S.time-before.time;if(td)out.unshift({text:`时间 +${td}小时`,good:false});for(const [k,m] of Object.entries(personMeta)){const d=S.relations[k]-before.relations[k];if(d)out.push({text:`${m.name}关系 ${d>0?"+":""}${d}`,good:d>0})}for(const [k,m] of Object.entries(itemMeta)){const d=(S.inventory[k]||0)-(before.inventory[k]||0);if(d)out.push({text:`${m.name} ${d>0?"+":""}${d}`,good:d>0})}return out}
function save(show=false){if(!gameStarted)return;localStorage.setItem(SAVE_KEY,JSON.stringify(S));if(show)toast("游戏已保存")}
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;S=merge(JSON.parse(raw));return true}catch{return false}}
function addLog(text,changeList=[]){S.logs.push({day:S.day,time:S.time,text,changes:changeList});S.logs=S.logs.slice(-60);save();renderLog()}
function renderLog(){const list=S.logs.filter(x=>x.day===S.day);$("log").innerHTML=list.map(x=>`<article><time>${String(x.time).padStart(2,"0")}:00</time><div><p>${escapeHtml(x.text)}</p>${x.changes?.length?`<div class="changeRow">${x.changes.map(c=>`<span class="${c.good?"good":"bad"}">${escapeHtml(c.text)}</span>`).join("")}</div>`:""}</div></article>`).join("");requestAnimationFrame(()=>$("log").scrollTop=$("log").scrollHeight)}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(text){const t=$("toast");t.textContent=text;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2700)}
function close(id){$(id).classList.add("hidden")}
function closeTransient(){["actionModal","journalModal","shopModal"].forEach(close)}

function objective(){if(!S.morning)return["完成晨间治疗","治疗结束后，今天的场景行动才会开放。"];if(!S.clues.wristband)return["核对陌生腕带","调查病房床头柜，找到可以被正式复查的身份编号。"];if(!S.clues.notice)return["取得周期排班","周一、周三或周五前往护士站，抄录每周固定安排。"];if(!S.clues.nightRoster)return["让老张说出实情","茶包能打开话题；他观察过每周重复出现的院外人员。"];if(!S.clues.drugBatch)return["核对药品车批次","带着排班线索，在行政登记开放日观察药品车。"];if(!S.clues.records)return["复制正式病历","准备复写纸，保持足够信任，并利用已有身份与药品线索。"];if(!S.clues.maintenance)return["确认旧楼检修路线","经营陈伯关系，取得手电，再于工疗开放日检查维修门。"];return["自由准备逃离路线","证据链已经成立。继续经营人物与资源，比较三种离院方向。"]}
function render(){normalize();$("day").textContent=S.day;$("weekday").textContent=weekday();$("time").textContent=`${String(S.time).padStart(2,"0")}:00`;["energy","clarity","tokens","trust","suspicion","drug"].forEach(k=>$(k).textContent=S[k]);$("trustBar").style.width=S.trust+"%";$("suspicionBar").style.width=Math.min(100,S.suspicion/60*100)+"%";$("drugBar").style.width=S.drug+"%";$("timeProgress").style.width=Math.max(0,(S.time-8)/14*100)+"%";$("remaining").textContent=`今日剩余 ${Math.max(0,22-S.time)} 小时 · ${drugEffect().name}`;const done=Object.values(S.clues).filter(Boolean).length;$("objectiveProgress").style.width=done/6*100+"%";$("objectiveStep").textContent=`调查阶段 ${done} / 6`;const obj=objective();$("objectiveTitle").textContent=obj[0];$("objectiveText").textContent=obj[1];$("captionTitle").textContent=S.morning?"今天可以自由安排":"晨间治疗尚未完成";$("captionText").textContent=S.morning?"切换区域不推进时间；点击场景热点才会结算行动。":"护士林正在门口等你。完成治疗后才可以安排今天的行动。";const routeC=$("routeC");if(S.flags.guardGift){routeC.classList.remove("locked");routeC.innerHTML="<b>C · 夜班交换</b><span>周凯愿意延后补写一次巡逻记录，隐藏路线已经开启。</span>"}else{routeC.classList.add("locked");routeC.innerHTML="<b>C · 尚未发现</b><span>保安周凯掌握着一条不在公开排班上的路径。</span>"}renderSceneTabs();renderPeople();renderLog();if(done===6&&!S.chapterShown){S.chapterShown=true;setTimeout(()=>$("chapterModal").classList.remove("hidden"),450)}save()}
function sceneOpen(id){if(id==="workshop")return[2,4,6].includes(weekNo());if(id==="station")return S.trust>=40&&[1,3,5].includes(weekNo());return true}
function renderSceneTabs(){document.querySelectorAll(".sceneTab[data-scene]").forEach(b=>{const open=sceneOpen(b.dataset.scene);b.classList.toggle("locked",!open);b.classList.toggle("active",b.dataset.scene===S.scene);const small=b.querySelector("small");if(!open)small.textContent=b.dataset.scene==="station"&&S.trust<40?"信任不足":"今日关闭";else if(b.dataset.scene==="workshop")small.textContent="今日开放";else if(b.dataset.scene==="station")small.textContent="行政登记"})}
function switchScene(id,force=false){if(!force&&!S.morning){toast("先完成晨间治疗");return}if(!force&&!sceneOpen(id)){toast(`${scenes[id].title}今天不开放，请查看每周排班`);return}S.scene=id;const meta=scenes[id],stage=$("scene");stage.className=`scene ${id}`;$("sceneTitle").textContent=meta.title;$("sceneHint").textContent=meta.hint;stage.querySelectorAll(".hotspot").forEach(x=>x.remove());meta.hotspots.forEach(([action,label,x,y])=>{const b=document.createElement("button");b.className="hotspot";b.dataset.action=action;b.style.left=x+"%";b.style.top=y+"%";b.innerHTML=`<span>${label}</span>`;b.onclick=()=>openAction(action);stage.appendChild(b)});renderPeople();renderSceneTabs();save()}
function renderPeople(){const list=scenes[S.scene].people;$("people").innerHTML=list.map(id=>{const p=personMeta[id];return`<p><span class="avatar">${p.short}</span><b>${p.name}<small>关系 ${S.relations[id]}</small></b><em>${S.scene==="station"?"值班中":"在场"}</em></p>`}).join("")}

function openModalAction(title,text,choices,eyebrow="场景行动"){$("actionEyebrow").textContent=eyebrow;$("actionTitle").textContent=title;$("actionText").textContent=text;$("actionChoices").innerHTML="";choices.forEach(c=>{const b=document.createElement("button");b.disabled=!!c.disabled;b.innerHTML=`<b>${c.title}</b><span>${c.sub||""}</span>`;b.onclick=()=>c.run();$("actionChoices").appendChild(b)});$("actionModal").classList.remove("hidden")}
function actionTime(base){return Math.max(1,Math.ceil(base*drugEffect().time))}
function perform(baseHours,energyCost,message,fn=()=>{}){if(!S.morning){toast("先完成晨间治疗");return false}const hours=actionTime(baseHours);if(S.time+hours>22){toast(`今天剩余时间不足：需要 ${hours} 小时`);return false}const need=energyCost+drugEffect().energy;if(S.energy<need){toast(`体力不足：需要 ${need} 点`);return false}const before=snapshot();S.time+=hours;S.energy-=need;fn();normalize();const result=changes(before);addLog(message,result);close("actionModal");render();toast(result.map(x=>x.text).join(" · ")||message);if(S.suspicion>=60){triggerConfinement();return true}if(S.time>=22)setTimeout(()=>endDay(true),450);return true}
function gainRelation(id,n){S.relations[id]=clamp(S.relations[id]+n)}
function gainSkill(id,n){S.skills[id]=Math.min(5,Math.round((S.skills[id]+n/100*drugEffect().growth)*10)/10)}
function gainClue(id){if(S.clues[id])return;S.clues[id]=true;pendingClue=id;setTimeout(showPendingClue,180)}
function showPendingClue(){if(!pendingClue)return;const c=clueMeta[pendingClue];pendingClue=null;$("clueType").textContent=c.type;$("clueTitle").textContent=c.name;$("clueText").textContent=c.text;$("clueImpact").textContent=`后续影响：${c.impact}`;$("clueModal").classList.remove("hidden")}

function openAction(id){if(!S.morning){toast("先完成晨间治疗");return}const a={
  rest:()=>openModalAction("在床铺上休息","休息会推进时间，但能恢复体力、清醒并代谢药物。",[{title:"休息一会儿",sub:`${actionTime(2)} 小时 · 体力 +30 · 清醒 +12 · 药物 -7`,run:()=>perform(2,0,"你在病房休息，药物带来的迟钝感减轻了一些。",()=>{S.energy+=30;S.clarity+=12;S.drug-=7})}]),
  locker:()=>{close("actionModal");openJournal("items")},
  wristband:()=>S.clues.wristband?openModalAction("陌生腕带","编号 E2-071 与病历页码不一致。你已经把它记入调查记录。",[]):openModalAction("床头柜上的陌生腕带","塑料腕带写着另一个名字。单纯争辩没有用，但编号可以和正式记录交叉核对。",[{title:"逐项核对并记下编号",sub:`${actionTime(2)} 小时 · 体力 -6 · 观察成长`,run:()=>perform(2,6,"你记下腕带姓名、编号与病历页码之间的矛盾。",()=>{gainSkill("observe",35);gainClue("wristband")})}],"第一条线索"),
  exercise:()=>openModalAction("康复训练","训练能改善身体状态，但药物负荷越高，成长效率越低。",[{title:"完成一轮训练",sub:`${actionTime(3)} 小时 · 体力 -22 · 药物 -5 · 清醒 +6`,run:()=>perform(3,22,"你完成康复训练，身体活动让思路清醒了一些。",()=>{S.drug-=5;S.clarity+=6;S.suspicion-=1;gainSkill("fitness",45)})}]),
  zhang:talkZhang,chen:talkChen,guard:talkGuard,nurse:talkNurse,
  work:()=>openModalAction("工疗台","按要求组装病区用品。稳定工作能赚取积分，也能降低院方疑虑。",[{title:"完成一轮工疗",sub:`${actionTime(3)} 小时 · 体力 -18 · 积分 +9 · 信任 +2`,run:()=>perform(3,18,"你完成一轮工疗，领到院内积分。",()=>{S.tokens+=9;S.trust+=2;S.suspicion-=1})}]),
  laundry:()=>openModalAction("洗衣车","衣物和床单之间偶尔会夹着被遗漏的东西。",[{title:S.flags.laundryFound?"整理一车床单":"仔细检查每层床单",sub:S.flags.laundryFound?`${actionTime(2)} 小时 · 积分 +5`:`${actionTime(2)} 小时 · 发现一块香皂`,run:()=>perform(2,12,S.flags.laundryFound?"你完成洗衣整理，领到少量积分。":"你在床单夹层找到一块没有登记的香皂。",()=>{if(S.flags.laundryFound)S.tokens+=5;else{S.flags.laundryFound=true;S.inventory.soap++}})}]),
  notice:()=>S.clues.notice?openModalAction("每周排班公告",clueMeta.notice.text,[]):openModalAction("每周治疗与开放安排","公告上的固定星期比单次事件更有价值。它能让你预测哪些房间开放，以及什么时候人手最少。",[{title:"抄下完整排班",sub:`${actionTime(2)} 小时 · 观察成长 · 获得周期情报`,run:()=>perform(2,5,"你抄下每周重复的治疗、工疗和登记安排。",()=>{gainSkill("observe",30);gainClue("notice")})}],"周期情报"),
  cart:inspectCart,records:inspectRecords,maintenance:inspectMaintenance
};a[id]?.()}

function talkZhang(){const choices=[{title:"陪老张聊一会儿",sub:`${actionTime(2)} 小时 · 关系 +8 · 社交成长`,run:()=>perform(2,7,"老张提醒你：真正可靠的异常，总会按固定时间重复。",()=>{gainRelation("zhang",8);gainSkill("social",25)})}];if(!S.flags.zhangGift)choices.push({title:"送给他一包茶",sub:S.inventory.tea?`${actionTime(1)} 小时 · 茶包 -1 · 关系 +22 · 获得情报`:`需要茶包（可在小卖部购买）`,disabled:!S.inventory.tea,run:()=>perform(1,0,"老张接过茶，说出他连续三周记下的异常夜班人员。",()=>{S.inventory.tea--;S.flags.zhangGift=true;gainRelation("zhang",22);gainClue("nightRoster")})});openModalAction("老张","他以前做过记者，习惯把每天经过花园的人和时间都记在心里。",choices,"人物互动")}
function talkChen(){const choices=[{title:"问他旧楼结构",sub:`${actionTime(2)} 小时 · 关系 +8 · 社交成长`,run:()=>perform(2,7,"陈伯画了几条管线方向，但他说真正的检修门还需要当面确认。",()=>{gainRelation("chen",8);gainSkill("social",25)})}];if(!S.flags.chenGift)choices.push({title:"把点心分给陈伯",sub:S.inventory.snack?`${actionTime(1)} 小时 · 点心 -1 · 关系 +22 · 获得手电`:`需要点心`,disabled:!S.inventory.snack,run:()=>perform(1,0,"陈伯收下点心，把一只袖珍手电塞给你。",()=>{S.inventory.snack--;S.inventory.flashlight++;S.flags.chenGift=true;gainRelation("chen",22)})});openModalAction("陈伯","曾经的维修工。他不相信传闻，只相信墙后管线和门锁编号。",choices,"人物互动")}
function talkGuard(){const choices=[{title:"和他聊巡逻工作",sub:`${actionTime(2)} 小时 · 关系 +8 · 怀疑 -1`,run:()=>perform(2,6,"周凯抱怨固定巡逻太无聊，也透露周五晚的清点最缺人手。",()=>{gainRelation("guard",8);S.suspicion-=1;gainSkill("social",20)})}];if(!S.flags.guardGift)choices.push({title:"送一包速溶咖啡",sub:S.inventory.coffee?`${actionTime(1)} 小时 · 咖啡 -1 · 关系 +22 · 隐藏路线条件`:`需要速溶咖啡`,disabled:!S.inventory.coffee,run:()=>perform(1,0,"周凯收下咖啡，暗示某些夜班记录可以“晚一点再补”。",()=>{S.inventory.coffee--;S.flags.guardGift=true;gainRelation("guard",22)})});openModalAction("保安周凯","他负责工疗区和行政走廊巡逻。既是阻碍，也可能成为制度里最关键的缺口。",choices,"人物互动")}
function talkNurse(){openModalAction("护士林","她愿意为稳定的病人留下正式谈话记录。信任足够高时，这些记录会成为合法复核的基础。",[{title:"平静询问治疗安排",sub:`${actionTime(2)} 小时 · 关系 +8 · 信任 +3`,run:()=>perform(2,6,"护士林把你的问题写进正式记录，并解释了登记日的流程。",()=>{gainRelation("nurse",8);S.trust+=3;gainSkill("social",25)})}],"人物互动")}
function inspectCart(){if(!S.clues.notice){openModalAction("药品车","箱子和当日记录看起来没有规律。你需要先取得周期排班，才知道该核对哪一批。",[]);return}if(S.clarity<45){openModalAction("药品车","药物让编号在眼前重叠。至少需要 45 清醒才能完成这次比对。",[]);return}S.clues.drugBatch?openModalAction("重复药品批次",clueMeta.drugBatch.text,[]):openModalAction("核对药品车","排班表让你知道今天应该出现哪些药箱。比对批次需要保持注意，也可能引起值班人员怀疑。",[{title:"逐箱核对批次",sub:`${actionTime(3)} 小时 · 体力 -10 · 怀疑 +7 · 观察成长`,run:()=>perform(3,10,"你发现一组被重复登记的药品批次。",()=>{S.suspicion+=7;gainSkill("observe",45);gainClue("drugBatch")})}],"高风险调查")}
function inspectRecords(){const missing=[];if(!S.clues.wristband)missing.push("错误腕带编号");if(!S.clues.drugBatch)missing.push("重复药品批次");if(!S.inventory.carbon)missing.push("复写纸");if(S.trust<55)missing.push("信任 55");if(missing.length){openModalAction("病历柜","现在贸然翻找只会留下无法解释的风险。",[{title:"检查所需条件",sub:`还需要：${missing.join("、")}`,disabled:true}]);return}if(S.clues.records){openModalAction("病历复写页",clueMeta.records.text,[]);return}openModalAction("复制正式病历","你已经有明确编号、药品矛盾和不取走原件的方法。成功后会得到真正能被院外核验的证据。",[{title:"趁登记间隙复写记录",sub:`${actionTime(4)} 小时 · 复写纸 -1 · 怀疑 +12 · 关键证据`,run:()=>perform(4,14,"你复写了 E2-071 的历史页和药品领用页。",()=>{S.inventory.carbon--;S.suspicion+=12;gainSkill("observe",55);gainClue("records")})}],"关键调查")}
function inspectMaintenance(){const missing=[];if(S.relations.chen<25)missing.push("陈伯关系 25");if(!S.inventory.flashlight)missing.push("袖珍手电");if(!S.clues.nightRoster)missing.push("异常夜班记录");if(missing.length){openModalAction("锁住的维修门","门锁、黑暗和巡逻时间都不能只靠运气解决。",[{title:"检查所需条件",sub:`还需要：${missing.join("、")}`,disabled:true}]);return}if(S.clues.maintenance){openModalAction("旧楼检修路线",clueMeta.maintenance.text,[]);return}openModalAction("确认检修路线","陈伯的管线记忆、老张的夜班观察和手电让这次调查有了完整依据。",[{title:"检查门锁与墙上编号",sub:`${actionTime(4)} 小时 · 体力 -18 · 怀疑 +9 · 路线线索`,run:()=>perform(4,18,"你确认了西侧检修廊与夜班巡逻之间的空档。",()=>{S.suspicion+=9;gainSkill("observe",45);gainClue("maintenance")})}],"路线调查")}

function resolveTreatment(kind,roll=Math.random()){const before=snapshot();let msg="";if(kind==="full"){S.trust+=6;S.suspicion-=4;S.drug+=18;S.clarity-=12;S.energy-=4;gainRelation("nurse",2);msg="你按医嘱服药，院方评价改善，但思路变得迟钝。"}else if(kind==="half"){if(roll<.45){S.trust+=3;S.suspicion-=2;S.drug+=8;S.clarity-=5;msg="你只服下一半，护士没有察觉。"}else if(roll<.8){S.trust-=2;S.suspicion+=6;S.drug+=8;S.clarity-=5;msg="护士注意到吞咽动作，记录上多了一个问号。"}else{S.trust-=6;S.suspicion+=11;S.drug+=14;S.clarity-=9;msg="藏起的半片药被发现。"}}else{if(S.day<2){toast("设法避开从第 2 天开始解锁");return}if(roll<.45){S.trust-=2;S.suspicion+=9;S.clarity+=3;msg="你避开服药，但异常表现被写进记录。"}else if(roll<.75){S.trust-=7;S.suspicion+=15;msg="护士发现药片没有减少，你被列为重点观察。"}else{S.trust-=10;S.suspicion+=22;S.drug+=36;S.clarity-=25;S.energy-=10;msg="你被当场发现并遭到强制服药。"}}S.morning=true;normalize();close("morningModal");addLog(msg,changes(before));render();if(S.suspicion>=60)triggerConfinement();else toast(msg)}
function showMorning(){S.morning=false;$("avoidTreatment").disabled=S.day<2;$("morningModal").classList.remove("hidden");render()}
function endDay(auto=false){if(S.dayEnded)return;if(!auto&&S.time<18&&!confirm("现在结束今天，会放弃剩余时间。确定继续吗？"))return;S.dayEnded=true;$("dayEndTitle").textContent=`第 ${S.day} 天 · ${weekday()}结束`;$("dayEndText").textContent="正常过夜恢复体力与清醒，并降低药物负荷；信任、怀疑、关系、物品和线索保持不变。";$("dayEndStats").innerHTML=`<div><b>+42</b><br><small>体力</small></div><div><b>+20</b><br><small>清醒</small></div><div><b>-10</b><br><small>药物</small></div><div><b>${S.suspicion}</b><br><small>怀疑不变</small></div>`;closeTransient();$("dayEndModal").classList.remove("hidden");save()}
function nextDay(){const before=snapshot();S.day++;S.time=8;S.energy+=42;S.clarity+=20;S.drug-=10;S.dayEnded=false;S.morning=false;S.scene="ward";normalize();close("dayEndModal");S.logs.push({day:S.day,time:8,text:`第 ${S.day} 天（${weekday()}）开始。今日开放区域已经更新。`,changes:changes(before).filter(x=>!x.text.startsWith("时间"))});switchScene("ward",true);showMorning();save()}
function triggerConfinement(){pendingClue=null;S.time=22;S.trust-=8;S.drug+=36;S.clarity-=30;S.energy-=10;S.suspicion=50;normalize();closeTransient();close("clueModal");addLog("怀疑达到 60，当前行动被中断。你被带进小黑屋并强制服药。",[]);$("confinementModal").classList.remove("hidden");render()}
function finishConfinement(){close("confinementModal");S.day++;S.time=8;S.energy+=25;S.drug-=10;S.clarity+=8;S.dayEnded=false;S.morning=false;S.scene="ward";normalize();S.logs.push({day:S.day,time:8,text:`隔离结束。第 ${S.day} 天（${weekday()}）开始。`,changes:[]});switchScene("ward",true);showMorning()}

function openJournal(tab="clues"){document.querySelectorAll("[data-journal]").forEach(b=>b.classList.toggle("active",b.dataset.journal===tab));let html="";if(tab==="clues")html=`<div class="recordGrid">${Object.entries(clueMeta).map(([k,c])=>`<article class="record ${S.clues[k]?"":"locked"}"><b>${S.clues[k]?c.name:"尚未取得"}</b><span>${S.clues[k]?c.text:"继续推进当前目标，线索会在正确的前置条件下出现。"}</span></article>`).join("")}</div>`;if(tab==="items")html=`<div class="recordGrid">${Object.entries(itemMeta).map(([k,m])=>`<article class="record ${(S.inventory[k]||0)?"":"locked"}"><b>${m.name} ×${S.inventory[k]||0}</b><span>${m.desc}</span>${(k==="soap"&&S.inventory[k])?`<div class="itemActions"><button data-use="soap">使用</button></div>`:""}</article>`).join("")}</div>`;if(tab==="relations")html=`<div class="recordGrid">${Object.entries(personMeta).map(([k,p])=>`<article class="record"><b>${p.name} · ${S.relations[k]}</b><span>${k==="guard"?"巡逻规则、行政区和隐藏离院路线。":k==="chen"?"维修结构、工具和旧楼通道。":k==="zhang"?"周期观察、院外人员和异常夜班。":"正式记录、院方信任和紧急复核。"}</span></article>`).join("")}</div>`;if(tab==="rules")html=`<div class="recordGrid"><article class="record"><b>体力</b><span>执行行动需要体力。休息、点心和过夜可以恢复。</span></article><article class="record"><b>清醒</b><span>低于 45 时无法完成精细比对；药物和强制事件会降低清醒。</span></article><article class="record"><b>药物负荷</b><span>越高，行动耗时和体力附加消耗越大，能力成长效率越低。</span></article><article class="record"><b>信任与怀疑</b><span>低信任会失去正式调查机会；怀疑达到 60 会立即触发隔离。</span></article></div>`;$("journalContent").innerHTML=html;$("journalContent").querySelectorAll("[data-use]").forEach(b=>b.onclick=()=>useItem(b.dataset.use));$("journalModal").classList.remove("hidden")}
function useItem(id){if(id==="soap"&&S.inventory.soap){const before=snapshot();S.inventory.soap--;S.trust+=2;S.suspicion-=6;addLog("你整理好个人状态，查房记录变得稳定。",changes(before));render();openJournal("items")}}
function openShop(){if(!S.morning){toast("先完成晨间治疗");return}shopFirst=true;renderShop();$("shopModal").classList.remove("hidden")}
function renderShop(){$("shopRule").textContent=shopFirst?"本次第一次成功购买会推进 1 小时；继续购买不再推进时间。":"本次首购时间已经结算，继续购买不再推进时间。";$("shopGrid").innerHTML=Object.entries(itemMeta).filter(([,m])=>m.price!==null).map(([k,m])=>`<article class="shopItem"><b>${m.name} · ${m.price} 积分</b><small>${m.desc}</small><button data-buy="${k}">购买</button></article>`).join("");$("shopGrid").querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>buyItem(b.dataset.buy))}
function buyItem(id){const m=itemMeta[id];if(S.tokens<m.price){toast("积分不够");return}if(shopFirst&&S.time>=22){toast("今天没有时间完成首购");return}const before=snapshot();if(shopFirst){S.time++;shopFirst=false}S.tokens-=m.price;S.inventory[id]++;addLog(`你在小卖部购买了${m.name}。`,changes(before));renderShop();render();if(S.time>=22){close("shopModal");setTimeout(()=>endDay(true),350)}}

function startGame(){gameStarted=true;close("titleScreen");const startScene=sceneOpen(S.scene)?S.scene:"ward";switchScene(startScene,true);render();if(!S.morning&&!S.dayEnded)setTimeout(showMorning,180);else if(S.dayEnded){S.dayEnded=false;endDay(true)}}
function newGame(){if(localStorage.getItem(SAVE_KEY)&&!confirm("开始新游戏会覆盖当前存档，确定继续吗？"))return;S=defaultState();localStorage.removeItem(SAVE_KEY);startGame()}
function continueGame(){if(load())startGame();else toast("没有可用存档")}

document.querySelectorAll(".sceneTab[data-scene]").forEach(b=>b.onclick=()=>switchScene(b.dataset.scene));
document.querySelectorAll("[data-treatment]").forEach(b=>b.onclick=()=>resolveTreatment(b.dataset.treatment));
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>close(b.dataset.close));
document.querySelectorAll("[data-journal]").forEach(b=>b.onclick=()=>openJournal(b.dataset.journal));
$("newGameBtn").onclick=newGame;$("continueBtn").onclick=continueGame;$("closeAction").onclick=()=>close("actionModal");$("shopBtn").onclick=openShop;$("journalBtn").onclick=()=>openJournal("clues");$("relationBtn").onclick=()=>openJournal("relations");$("saveBtn").onclick=()=>save(true);$("endDayBtn").onclick=()=>endDay(false);$("nextDayBtn").onclick=nextDay;$("finishConfinementBtn").onclick=finishConfinement;$("keepPlayingBtn").onclick=()=>close("chapterModal");

S=defaultState();if(!localStorage.getItem(SAVE_KEY))$("continueBtn").classList.add("hidden");switchScene("ward",true);render();
window.__escapeV3={getState:()=>JSON.parse(JSON.stringify(S)),reset(){S=defaultState();localStorage.removeItem(SAVE_KEY);render()},resolveTreatment:(k,r)=>resolveTreatment(k,r),openAction,perform,buyItem,nextDay,switchScene};
